#!/bin/sh
# /usr/lib/wan-affinity/apply-affinity.sh
#
# Shared apply helper for per-device WAN affinity. Reads the persistent lock
# lists, regenerates the nft marking chain, reloads fw4, and runs the failover
# hook so the change is live immediately. Called by both
# scripts/configure-wan-affinity.sh (installer) and the wan-affinity CGI (web UI),
# so there is one source of truth for "turn the lists into live routing".
#
# Source of truth:
#   /etc/wan-affinity/claro.list  - one MAC per line -> Claro (wan2), mark 0x20000
#   /etc/wan-affinity/vivo.list   - one MAC per line -> Vivo  (wan1), mark 0x10000
#   (blank lines and # comments ignored; unlisted LAN devices default to Vivo.)
#
# Idempotent. Backs up the replaced nft file (keeps the 5 most recent). Aborts on
# a malformed MAC rather than guessing.

set -eu

WA_DIR=${WA_DIR:-/etc/wan-affinity}
CLARO_LIST="$WA_DIR/claro.list"
VIVO_LIST="$WA_DIR/vivo.list"
NFT_DIR=/etc/nftables.d
NFT_FILE="$NFT_DIR/20-wan-affinity.nft"
PT_FILE=/usr/share/omr/post-tracking.d/098-wan-affinity
TS=$(date +%s)

# Read a list file -> space-separated, lowercased, validated MACs.
_read_list() {
	[ -f "$1" ] || return 0
	while IFS= read -r line; do
		m=$(echo "$line" | sed 's/#.*//; s/[[:space:]]//g' | tr 'A-F' 'a-f')
		[ -z "$m" ] && continue
		echo "$m" | grep -qE '^([0-9a-f]{2}:){5}[0-9a-f]{2}$' || {
			echo "ERROR: invalid MAC '$line' in $1 (expected aa:bb:cc:dd:ee:ff)" >&2
			exit 1
		}
		printf '%s ' "$m"
	done < "$1"
}

# space-separated MACs -> "aa:.., bb:.., cc:.." nft set body
_set_body() {
	_out=""
	for m in $1; do
		if [ -z "$_out" ]; then _out="$m"; else _out="$_out, $m"; fi
	done
	echo "$_out"
}

CLARO_MACS=$(_read_list "$CLARO_LIST")
VIVO_MACS=$(_read_list "$VIVO_LIST")

# ---- regenerate nft marking chain (empty sets omitted; nft rejects `{ }`) ----
mkdir -p "$NFT_DIR"
[ -f "$NFT_FILE" ] && cp "$NFT_FILE" "$NFT_FILE.bak.$TS"

{
	echo "# Generated by apply-affinity.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "# Per-device WAN affinity. 0x20000 -> Claro (table 101), 0x10000 -> Vivo (table 100)."
	echo "chain wan_affinity {"
	echo "    type filter hook prerouting priority -150; policy accept;"
	if [ -n "$(echo "$CLARO_MACS" | tr -d ' ')" ]; then
		echo "    ether saddr { $(_set_body "$CLARO_MACS") } meta mark set meta mark | 0x20000 counter comment \"pin Claro\""
	fi
	if [ -n "$(echo "$VIVO_MACS" | tr -d ' ')" ]; then
		echo "    ether saddr { $(_set_body "$VIVO_MACS") } meta mark set meta mark | 0x10000 counter comment \"pin Vivo\""
	fi
	echo "}"
} > "$NFT_FILE"

# prune old backups, keep 5 newest
ls -1t "$NFT_FILE".bak.* 2>/dev/null | tail -n +6 | while read -r f; do rm -f "$f"; done

# ---- apply firewall + routing now -------------------------------------------
fw4 reload >/dev/null 2>&1 || /etc/init.d/firewall reload >/dev/null 2>&1 || true

# Drop any legacy pri-50 br-lan->100 rule, then run the failover hook to build
# tables 100/101 and (re)install the pri 40/41/45 rules.
_i=0
while ip rule show | grep -qE "^50:[[:space:]].*iif br-lan lookup 100" && [ "$_i" -lt 16 ]; do
	ip rule del priority 50 iif br-lan lookup 100 2>/dev/null
	_i=$((_i + 1))
done
[ -x "$PT_FILE" ] && "$PT_FILE" || true
