#!/bin/sh
# Configure per-device WAN affinity on NexusGate (OpenMPTCProuter, dual-WAN, no
# VPS bonding). Replaces the ECMP load-balancer (099-ecmp-balance) and the older
# 098-vivo-pin with a deterministic, single-nexthop-per-device model:
#
#   - Vivo (wan1) is the DEFAULT WAN for every LAN device.
#   - MACs in CLARO_MACS are routed via Claro (wan2)  (mark 0x20000 -> table 101).
#   - MACs in VIVO_MACS are explicitly pinned to Vivo (mark 0x10000 -> table 100).
#   - Each table holds ONE nexthop, so a device's flows never split across two
#     public IPs mid-session -> streaming/gaming stay stable.
#   - Automatic failover + shift-back is handled by 098-wan-affinity each tracker
#     tick (rewrites the single nexthop of tables 100/101 from live WAN state).
#
# Idempotent. Backs up replaced files. Re-run after OMR package upgrades.
#
# Usage:
#   CLARO_MACS="aa:bb:cc:dd:ee:ff 11:22:33:44:55:66" sh configure-wan-affinity.sh
#   VIVO_MACS="..." overrides the Vivo lock list (defaults to current deployment).
#
# Deploy from a workstation (scp is unavailable on this router):
#   cat configure-wan-affinity.sh | ssh root@192.168.100.1 'CLARO_MACS="..." sh -s'

set -eu

# ---- Lock lists -------------------------------------------------------------
# Claro-only devices (streaming). Edit / pass via CLARO_MACS env.
CLARO_MACS=${CLARO_MACS:-"40:f6:bc:38:df:7c 44:d5:cc:e5:ad:a7 1c:fe:2b:f3:84:fc a8:a0:92:2f:9a:dc"}

# Vivo-pinned devices (current deployment default).
VIVO_MACS=${VIVO_MACS:-"06:72:3d:90:06:10 22:f6:ca:e4:09:46 34:29:8f:70:87:c8 48:e1:ca:06:f4:12 4e:42:43:17:1d:6f a4:6b:40:32:23:20 bc:35:1e:a3:f1:5d be:53:2a:62:8b:dd e0:85:4d:46:3d:6e f4:d4:88:66:07:9c fa:b3:8b:3c:da:f1"}

NFT_DIR=/etc/nftables.d
NFT_FILE="$NFT_DIR/20-wan-affinity.nft"
PT_DIR=/usr/share/omr/post-tracking.d
PT_FILE="$PT_DIR/098-wan-affinity"
TS=$(date +%s)

# ---- Helpers ----------------------------------------------------------------
# Normalise a space-separated MAC list to a lowercase comma+newline nft set body.
# Validates each MAC; aborts on a malformed entry (never guess a MAC).
_mac_set_body() {
	_out=""
	for m in $1; do
		ml=$(echo "$m" | tr 'A-F' 'a-f')
		echo "$ml" | grep -qE '^([0-9a-f]{2}:){5}[0-9a-f]{2}$' || {
			echo "ERROR: invalid MAC '$m' (expected aa:bb:cc:dd:ee:ff)" >&2
			exit 1
		}
		if [ -z "$_out" ]; then _out="$ml"; else _out="$_out, $ml"; fi
	done
	echo "$_out"
}

# ---- 1. Generate the nft marking chain --------------------------------------
mkdir -p "$NFT_DIR"
[ -f "$NFT_FILE" ] && cp "$NFT_FILE" "$NFT_FILE.bak.$TS"

{
	echo "# Generated by configure-wan-affinity.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "# Per-device WAN affinity. 0x20000 -> Claro (table 101), 0x10000 -> Vivo (table 100)."
	echo "chain wan_affinity {"
	echo "    type filter hook prerouting priority -150; policy accept;"
	if [ -n "$(echo "$CLARO_MACS" | tr -d ' ')" ]; then
		echo "    ether saddr { $(_mac_set_body "$CLARO_MACS") } meta mark set meta mark | 0x20000 counter comment \"pin Claro\""
	fi
	if [ -n "$(echo "$VIVO_MACS" | tr -d ' ')" ]; then
		echo "    ether saddr { $(_mac_set_body "$VIVO_MACS") } meta mark set meta mark | 0x10000 counter comment \"pin Vivo\""
	fi
	echo "}"
} > "$NFT_FILE"

# Remove the superseded vivo-pin nft file.
[ -f "$NFT_DIR/20-vivo-pin.nft" ] && mv "$NFT_DIR/20-vivo-pin.nft" "$NFT_DIR/20-vivo-pin.nft.retired.$TS"

# ---- 2. Install the post-tracking failover script ---------------------------
# (The 098-wan-affinity body ships alongside this script; deploy both. If only
#  this file is piped in, write the companion from the repo separately.)
if [ -f "$(dirname "$0")/wan-affinity/098-wan-affinity" ]; then
	cp "$(dirname "$0")/wan-affinity/098-wan-affinity" "$PT_FILE"
	chmod +x "$PT_FILE"
fi

# Retire ECMP + old pin post-tracking scripts.
for f in 098-vivo-pin 099-ecmp-balance; do
	[ -f "$PT_DIR/$f" ] && mv "$PT_DIR/$f" "$PT_DIR/$f.retired.$TS"
done
for f in "$PT_DIR"/099-ecmp-balance.bak-*; do
	[ -f "$f" ] && rm -f "$f"
done

# ---- 3. Apply firewall + routing now ----------------------------------------
fw4 reload >/dev/null 2>&1 || /etc/init.d/firewall reload >/dev/null 2>&1 || true

# Drop the legacy pri-50 br-lan->100 rule if a prior install added it, then run
# the failover script to build tables 100/101 and install pri 40/41/45 rules.
# (OMR core's pri-50 "iif br-lan lookup 991337" ECMP rule is left in place; the
# pri-45 LAN-default rule shadows it -- see 098-wan-affinity.)
_i=0
while ip rule show | grep -qE "^50:[[:space:]].*iif br-lan lookup 100" && [ "$_i" -lt 16 ]; do
	ip rule del priority 50 iif br-lan lookup 100 2>/dev/null
	_i=$((_i + 1))
done
[ -x "$PT_FILE" ] && "$PT_FILE" || true

# ---- 4. Report --------------------------------------------------------------
echo "== nft chain =="
nft list chain inet fw4 wan_affinity 2>/dev/null || echo "(wan_affinity chain not loaded - check fw4 reload)"
echo
echo "== ip rules (affinity) =="
ip rule show | grep -E "lookup (100|101)|iif br-lan" || true
echo
echo "== table 100 (Vivo default) =="; ip route show table 100
echo "== table 101 (Claro) =="; ip route show table 101
echo
echo "Claro MACs: $CLARO_MACS"
echo "Done. Verify a Claro device shows the Claro public IP (curl ifconfig.me) and a"
echo "default device shows the Vivo public IP, both stable across repeated calls."
